import { SubmitButton } from "submitbutton.slint";
import { EntryForm } from "entryform.slint";

        // SubmitButton {
        //     clicked => {
        //         // invokes callback 'send-entry' send_entry in main.rs)
        //         if ( company != "" && role != "" && pay != "" && area != "" && sector != "" && level != "" && requirements!= "" && date_applied != "" && stage != "" && close_date != "" && notes != "") {
        //             root.output = "Sending Entry";
        //             send-entry({
        //                 company: company,
        //                 role: role,
        //                 pay: pay,
        //                 area: area,
        //                 sector: sector,
        //                 level: level,
        //                 requirements: requirements,
        //                 date_applied: date_applied,
        //                 stage: stage,
        //                 close_date: close_date,
        //                 notes: notes,
        //             });
        //             // company = "";
        //             // role = "";
        //             // pay = "";
        //             // area = "";
        //             // sector = "";
        //             // level = "";
        //             // requirements= "";
        //             // date_applied = "";
        //             // stage = "";
        //             // close_date = "";
        //             // notes = "";
        //         }
        //         else {
        //             root.output = "Ensure all fields are entered..."
        //         }
        //     }
        // }
