import { Button, StandardButton, GridBox } from "std-widgets.slint";
import { SubmitButton } from "./components/submitButton.slint";
import { OutputModal, Output } from "./components/outputmodal.slint";
import { OkButton } from "./components/okbutton.slint";
import { EntryForm } from "./components/entryform.slint";

export component AppWindow inherits Window {
    in-out property <string> company;
    in-out property <string> role;
    in-out property <string> pay;
    in-out property <string> area;
    in-out property <string> sector;
    in-out property <string> level;
    in-out property <string> requirements;
    in-out property <string> date_applied;
    in-out property <string> stage;
    in-out property <string> close_date;
    in-out property <string> notes;
    in-out property <string> output:"";
    in property <string> select_result: "";

    callback send-entry({
        company: string,
        role:string,
        pay:string,
        area: string,
        sector: string,
        level: string,
        requirements: string,
        date_applied: string,
        stage: string,
        close_date: string,
        notes: string
    });
    callback get-entries();

    title:"Apprenticeship Tracker";
    min-width: 900px;
    min-height: 450px;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            EntryForm {
                company <=> company;
                role <=> role;
                pay <=> pay;
                area <=> area;
                sector <=> sector;
                level <=> level;
                requirements <=> requirements;
                date_applied <=> date_applied;
                stage <=> stage;
                close_date <=> close_date;
                notes <=> notes;
            }
        }
        Row {
            SubmitButton {
                clicked => {
                    root.output = "Sending Entry";
                    root.send-entry({
                        company: "UBS",
                        role: "SRE",
                        pay: "27000",
                        area: "stevenage",
                        sector: "tech",
                        level: "0",
                        requirements: "n/a",
                        date_applied: "20/10/2024",
                        stage: "Final interviews",
                        close_date: "30/10/2024",
                        notes: "Test input",
                    });
                }
            }
        }
        Row {
            Button {
                text: "Get";
                clicked => {
                    root.get-entries()
                }
            }
        }
        Row {
            Rectangle {
                Text {
                    text: select_result;
                }
            }
        }
    }
    OutputModal {
        visible: root.output != "";
        GridLayout {
            Row {
                Output {
                    text: root.output;
                }
            }
            Row {
                OkButton {
                    clicked => {
                        root.output = ""
                    }
                }
            }
        }
    }
}
